/**
 * Operation real wave API
 * MSR Soundtrack audio management website\'s schema 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AlbumSummary } from '../models/AlbumSummary';
import { HttpFile } from '../http/http';

export class AlbumListResponse {
    'albums': Array<AlbumSummary>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "albums",
            "baseName": "albums",
            "type": "Array<AlbumSummary>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AlbumListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
