openapi: '3.1.0'
info:
  title: Operation real wave API
  description: |
    MSR Soundtrack audio management website's schema
  version: 0.0.1
servers:
  - url: http://localhost:3000/api/
    description: Dev API (vite dev server proxy required)
tags:
  - name: album
    description: アルバム
  - name: songs
    description: 楽曲
  - name: file
    description: ファイル管理
paths:
  /albums:
    get:
      summary: アルバムの一覧を取得
      tags:
        - album
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlbumListResponse'
  /album/{cid}:
    get:
      summary: 指定したアルバムの楽曲一覧を取得
      tags:
        - album
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: アルバムの cid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongListResponse'
    post:
      summary: 指定したアルバムの楽曲すべてのダウンロードを開始する
      tags:
        - album
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: アルバムの cid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchAlbumResponse'
    delete:
      summary: 指定したアルバムをファイルシステム上から削除する
      tags:
        - album
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: アルバムの cid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongListResponse'
  /song/{cid}:
    get:
      summary: 指定した楽曲の状態を取得
      tags:
        - songs
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: 楽曲の cid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongStatusResponse'
    post:
      summary: 指定した楽曲のダウンロードを開始する
      tags:
        - songs
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: 楽曲の cid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchSongResponse'
    delete:
      summary: 指定した楽曲をファイルシステム上から削除する
      tags:
        - songs
      parameters:
        - in: path
          name: cid
          schema:
            type: string
          required: true
          description: 楽曲の cid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongStatusResponse'

components:
  schemas:
    FileStatus:
      type: string
      enum:
        - NOT_EXISTS
        - BROKEN
        - EXISTS
    Album:
      type: object
      required:
        - cid
        - name
        - artistes
        - status
        - coverPath
      properties:
        cid:
          type: string
          example: 8932
        name:
          type: string
          example: Mystic Light Quest
        artistes:
          type: array
          items:
            type: string
          example: [塞壬唱片-MSR]
        status:
          $ref: '#/components/schemas/FileStatus'
        coverPath:
          type: string
          example: ./path/to/album/cover.png
    Song:
      type: object
      required:
        - cid
        - name
        - artistes
        - status
        - filePath
      properties:
        cid:
          type: string
          example: 8932
        name:
          type: string
          example: Mystic Light Quest
        artistes:
          type: array
          items:
            type: string
          example: [塞壬唱片-MSR]
        status:
          $ref: '#/components/schemas/FileStatus'
        filePath:
          type: string
          example: /fullpath/to/song/file.flac
    AlbumListResponse:
      type: object
      required:
        - albums
      properties:
        albums:
          type: array
          items:
            $ref: '#/components/schemas/Album'
    FetchAlbumResponse:
      type: object
      required:
        - queuedSongs
      properties:
        queuedSongs:
          type: array
          items:
            $ref: '#/components/schemas/Song'
    SongListResponse:
      type: object
      required:
        - songs
      properties:
        songs:
          type: array
          items:
            $ref: '#/components/schemas/Song'
    SongStatusResponse:
      type: object
      required:
        - song
      properties:
        song:
          $ref: '#/components/schemas/Song'
    FetchSongResponse:
      type: object
      required:
        - song
      properties:
        song:
          $ref: '#/components/schemas/Song'