openapi: 3.0.0
info:
  title: Operation real wave API
  version: 0.0.1
  description: MSR Soundtrack audio management website's schema
tags:
  - name: album
  - name: songs
paths:
  /album/{cid}:
    delete:
      operationId: deleteAlbum
      summary: 指定したアルバムをファイルシステム上から削除する
      parameters:
        - name: cid
          in: path
          required: true
          description: アルバムの cid
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlbumSongListResponse'
      tags:
        - album
    get:
      operationId: getAlbumSongs
      summary: 指定したアルバムの楽曲一覧を取得
      parameters:
        - name: cid
          in: path
          required: true
          description: アルバムの cid
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlbumSongListResponse'
      tags:
        - album
    post:
      operationId: fetchAlbumSongs
      summary: 指定したアルバムの楽曲すべてのダウンロードを開始する
      parameters:
        - name: cid
          in: path
          required: true
          description: アルバムの cid
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchAlbumResponse'
      tags:
        - album
  /albums:
    get:
      operationId: getAlbums
      summary: アルバムの一覧を取得
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlbumListResponse'
      tags:
        - album
  /song/{cid}:
    delete:
      operationId: deleteSong
      summary: 指定した楽曲をファイルシステム上から削除する
      parameters:
        - name: cid
          in: path
          required: true
          description: 楽曲の cid
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongStatusResponse'
      tags:
        - songs
    get:
      operationId: getSongStatus
      summary: 指定した楽曲の状態を取得
      parameters:
        - name: cid
          in: path
          required: true
          description: 楽曲の cid
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SongStatusResponse'
      tags:
        - songs
    post:
      operationId: fetchSong
      summary: 指定した楽曲のダウンロードを開始する
      parameters:
        - name: cid
          in: path
          required: true
          description: 楽曲の cid
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchSongResponse'
      tags:
        - songs
components:
  schemas:
    Album:
      type: object
      required:
        - cid
        - name
        - songs
        - status
        - coverPath
      properties:
        cid:
          type: string
        name:
          type: string
        songs:
          type: array
          items:
            $ref: '#/components/schemas/Song'
        status:
          $ref: '#/components/schemas/FileStatus'
        coverPath:
          type: string
    AlbumListResponse:
      type: object
      required:
        - albums
      properties:
        albums:
          type: array
          items:
            $ref: '#/components/schemas/AlbumSummary'
    AlbumSongListResponse:
      type: object
      required:
        - album
      properties:
        album:
          $ref: '#/components/schemas/Album'
    AlbumSummary:
      type: object
      required:
        - cid
        - name
        - artistes
        - status
        - coverPath
      properties:
        cid:
          type: string
        name:
          type: string
        artistes:
          type: array
          items:
            type: string
        status:
          $ref: '#/components/schemas/FileStatus'
        coverPath:
          type: string
    FetchAlbumResponse:
      type: object
      required:
        - queuedSongs
      properties:
        queuedSongs:
          type: array
          items:
            $ref: '#/components/schemas/Song'
    FetchSongResponse:
      type: object
      required:
        - song
      properties:
        song:
          $ref: '#/components/schemas/Song'
    FileStatus:
      type: string
      enum:
        - NOT_EXISTS
        - BROKEN
        - EXISTS
    Song:
      type: object
      required:
        - cid
        - name
        - artistes
        - status
        - filePath
      properties:
        cid:
          type: string
        name:
          type: string
        artistes:
          type: array
          items:
            type: string
        status:
          $ref: '#/components/schemas/FileStatus'
        filePath:
          type: string
    SongStatusResponse:
      type: object
      required:
        - song
      properties:
        song:
          $ref: '#/components/schemas/Song'
