/**
 * Operation real wave API
 * MSR Soundtrack audio management website\'s schema 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Album } from '../models/Album.ts';
import { HttpFile } from '../http/http.ts';

export class AlbumSongListResponse {
    'album': Album;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "album",
            "baseName": "album",
            "type": "Album",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AlbumSongListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
