/**
 * Operation real wave API
 * MSR Soundtrack audio management website\'s schema
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Song } from '../models/Song.ts';
import { HttpFile } from '../http/http.ts';

export class FetchAlbumResponse {
    'queuedSongs': Array<Song>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "queuedSongs",
            "baseName": "queuedSongs",
            "type": "Array<Song>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FetchAlbumResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
