/**
 * Operation real wave API
 * MSR Soundtrack audio management website\'s schema
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export enum FileStatus {
    NotExists = "NOT_EXISTS",
    Broken = "BROKEN",
    Exists = "EXISTS",
}
