/**
 * (c) MONSTER SIREN RECORD
 * MSR original soundtrack website\'s schema https://monster-siren.hypergryph.com 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AlbumDetails } from '../models/AlbumDetails.ts';
import { HttpFile } from '../http/http.ts';

export class AlbumDetailResponse {
    'code': number;
    'msg': string;
    'data': AlbumDetails;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number",
            "format": ""
        },
        {
            "name": "msg",
            "baseName": "msg",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "AlbumDetails",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AlbumDetailResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

