/**
 * (c) MONSTER SIREN RECORD
 * MSR original soundtrack website\'s schema https://monster-siren.hypergryph.com
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MsrSong } from '../models/MsrSong.ts';
import { HttpFile } from '../http/http.ts';

export class MsrSongDetailsResponse {
    'code': number;
    'msg': string;
    'data': MsrSong;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "number",
            "format": ""
        },
        {
            "name": "msg",
            "baseName": "msg",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "MsrSong",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MsrSongDetailsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
