/**
 * (c) MONSTER SIREN RECORD
 * MSR original soundtrack website\'s schema https://monster-siren.hypergryph.com 
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class Song {
    'cid': string;
    'name': string;
    'albumCid': string;
    'sourceUrl': string;
    'lyricUrl': string;
    'mvUrl': string | null;
    'mvCoverUrl': string | null;
    'artists': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cid",
            "baseName": "cid",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "albumCid",
            "baseName": "albumCid",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceUrl",
            "baseName": "sourceUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "lyricUrl",
            "baseName": "lyricUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "mvUrl",
            "baseName": "mvUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "mvCoverUrl",
            "baseName": "mvCoverUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "artists",
            "baseName": "artists",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Song.attributeTypeMap;
    }

    public constructor() {
    }
}
